FIND_PATH(UV_INCLUDE_DIR NAMES uv.h)
FIND_LIBRARY(UV_LIBRARIES NAMES uv libuv)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(UV DEFAULT_MSG UV_LIBRARIES UV_INCLUDE_DIR)

IF(UV_INCLUDE_DIR AND UV_LIBRARIES)
  SET(UV_FOUND TRUE)
ELSE(UV_INCLUDE_DIR AND UV_LIBRARIES)
  SET(UV_FOUND FALSE)
ENDIF(UV_INCLUDE_DIR AND UV_LIBRARIES)

IF(UV_FOUND)
  MESSAGE(STATUS "Found libuv: ${UV_LIBRARIES}")
ELSE(UV_FOUND)
  MESSAGE(FATAL_ERROR "Could not find libuv.")
ENDIF(UV_FOUND)
