IF(SSL_EAY_DEBUG AND SSL_EAY_RELEASE)
   SET(LIB_FOUND 1)
ENDIF(SSL_EAY_DEBUG AND SSL_EAY_RELEASE)

FIND_PATH(CRYPTO_INCLUDE_DIR openssl/crypto.h )
FIND_LIBRARY(CRYPTO_LIBRARIES NAMES crypto )

IF(CRYPTO_INCLUDE_DIR AND CRYPTO_LIBRARIES)
   SET(CRYPTO_FOUND TRUE)
ELSE(CRYPTO_INCLUDE_DIR AND CRYPTO_LIBRARIES)
   SET(CRYPTO_FOUND FALSE)
ENDIF (CRYPTO_INCLUDE_DIR AND CRYPTO_LIBRARIES)

IF (CRYPTO_FOUND)
   IF (NOT Crypto_FIND_QUIETLY)
      MESSAGE(STATUS "Found libcrypto: ${CRYPTO_LIBRARIES}")
   ENDIF (NOT Crypto_FIND_QUIETLY)
ELSE (CRYPTO_FOUND)
   IF (Crypto_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could NOT find libcrypto")
   ENDIF (Crypto_FIND_REQUIRED)
ENDIF (CRYPTO_FOUND)

MARK_AS_ADVANCED(CRYPTO_INCLUDE_DIR CRYPTO_LIBRARIES)
