FIND_PATH(LIBUV_INCLUDE_DIR NAMES uv.h)
FIND_LIBRARY(LIBUV_LIBRARIES NAMES uv libuv)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBUV DEFAULT_MSG LIBUV_LIBRARIES LIBUV_INCLUDE_DIR)

IF(LIBUV_INCLUDE_DIR AND LIBUV_LIBRARIES)
  SET(LIBUV_FOUND TRUE)
ELSE(LIBUV_INCLUDE_DIR AND LIBUV_LIBRARIES)
  SET(LIBUV_FOUND FALSE)
ENDIF(LIBUV_INCLUDE_DIR AND LIBUV_LIBRARIES)

IF(LIBUV_FOUND)
  MESSAGE(STATUS "Found libuv: ${LIBUV_LIBRARIES}")
ELSE(LIBUV_FOUND)
  MESSAGE(FATAL_ERROR "Could not find libuv.")
ENDIF(LIBUV_FOUND)
